[package]
name = "thulani"
version = "0.1.0"
authors = ["Nathan Perry <avaglir@gmail.com>"]

[features]
default = ["diesel"]

[dependencies]
lazy_static = "1.0"
error-chain = "0.11.0"
log = "0.4"
typemap = "0.3.3"
url = "1.6.0"
dotenv = "0.11.0"
dotenv_codegen = "0.11.0"
chrono = "0.4"
fern = { version = "0.5", features = ["colored"] }
diesel = { version = "1.0.0", features = ["postgres"], optional = true }
cfg-if = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }

[dependencies.serenity]
# version = "~0.5"
default-features = false
features = ["builder", "cache", "client", "framework", "model", "utils", "voice", "standard_framework"]
git = "https://github.com/zeyla/serenity"
rev = "b71d99"
