version: '3'
services:
  thulani:
    image: thulani
    build: .
    depends_on:
      - db
      - migrate

    environment:
      DATABASE_URL: "postgres://thulani:clickheretodie@db/memes"
      RUST_BACKTRACE: 1

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: thulani
      POSTGRES_PASSWORD: clickheretodie
      POSTGRES_DB: memes

  migrate:
    build:
      context: .
      dockerfile: Dockerfile-migrate
    restart: on-failure
    depends_on:
      - db

volumes:
  db-data:
